# Generated by Django 3.1.2 on 2020-10-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('referrer', models.CharField(max_length=100)),
                ('count', models.CharField(max_length=100)),
            ],
        ),
    ]
